### ISSUE TITLE
Standardize file format for ease of creating front ends.

### ISSUE THREAD

**Issue by AgentEnder** [Ishaan28malik/Get-Dev-Resources#49]
This list should be created with machine parsing in mind. Currently there are some differences in how each category is laid out. Standardizing this would allow for easily spinning up front ends to display the info.

**Comment by Ishaan28malik** [comment]
@AgentEnder yeah this sounds good , can you work regarding this ? to make it in a particulare `format`

**Comment by AgentEnder** [comment]
I can, do you care to look at the current hugo impl from #50 before I start on it?

**Comment by Rac-Ro007** [comment]
Hey @Ishaan28malik , Please do have a review for the following PR #93, Added Resources and Practice for React Developers
